### ISSUE TITLE
Banner animation.

### ISSUE THREAD

**Issue by jesspaget** [jesspaget/dsn1676-term-project#1]
Hey @thomasjbradley

Right now my banner is flowing the way I want it to (similar to the stars we did in the in-class assignment) but I just want my background photo to flow and not the logo and title as well. Is there any easy way to achieve this without taking the logo and title out of the banner .div? I hope I worded that alright. 

Here's a screenshot and CSS 

![screen shot 2015-02-02 at 7 28 21 pm](https://cloud.githubusercontent.com/assets/6373211/6012101/c4be34d2-ab11-11e4-9fe2-eed4d85c32eb.png)

.banner {
    background-image: url(../images/banner.jpg);
    background-size: cover;
    width: 100%;
    position: relative;
    padding: 3rem 0;
    animation: scale 5s ease-in-out infinite alternate;
}

@keyframes scale {

```
0% {
    transform: scale(1,1);
}

100% {
    transform: scale(1.05,1.05);
}
```

}

**Comment by thomasjbradley** [comment]
Possibly instead of `position: relative` try adding `position: fixed`.
